sudo: required
dist: trusty
matrix:
    fast_finish: true

branches:
    only:
        - release
        - master

language: node_js
node_js:
    - '8.12.0'

install:
    - yarn install
    - yarn webpack

script:
    - yarn test
